hystrix:
  threadpool:
    default:
      coreSize: 200
      maxQueueSize: 200
      queueSizeRejectionThreshold: 200
server:
  port: 88
  servlet:
    context-path: /api
spring:
  application:
    name: evsmc-base-service
  cloud:
    consul:
      discovery:
        tags: version=1.0,desc=基础模块接口服务
        health-check-path: ${server.servlet.context-path}/actuator/health
      host: 10.11.6.1
      port: 8500
  profiles:
    active: dev
  messages:
    encoding: UTF-8
  mail:
    host: smtp.163.com
    protocol: smtp
    username: 15626911541@163.com
    password: a577900422Bc
  kafka:
    bootstrap-servers: 10.11.6.3:9092,10.11.6.7:9092
    producer:
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test-xiky_cp
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  scheduled:
    com:
      bitnei:
        cloud:
          common:
            handler:
              OfflineExportHandler:
                exportDirectory: /opt/export/offline
  servlet:
      multipart:
        max-file-size: 5Mb
        max-request-size: 10Mb
apollo:
  meta: http://10.11.6.1:8080
  cacheDir: data/config
  bootstrap:
    namespaces: app.evsmc-base-service, security, database, mybatis, redis , cto ,compent.feign
    enabled: true
app:
  id: ${spring.application.name}

kafka:
  consumers:
    us_ctrlrsp: -com.bitnei.cloud.compent.kafka.handler.UpdateStatusUploadHandler
      -com.bitnei.cloud.compent.kafka.handler.QueryResponseHandler
      -com.bitnei.cloud.compent.kafka.handler.SetupResponseHandler
      -com.bitnei.cloud.compent.kafka.handler.ControlResponseHandler
      -com.bitnei.cloud.compent.kafka.handler.UpdateCanSendResultHandler
      -com.bitnei.cloud.compent.kafka.handler.TerminalLockResponseHandler
    alarm_topic:
      -com.bitnei.cloud.fault.kafka.FaultAlarmVehicleHandler
    notice_topic:
      -com.bitnei.cloud.compent.kafka.handler.AbnormalVehicleHandler
    SYNC_VEHICLE_REG:
      -com.bitnei.cloud.compent.kafka.handler.PlatformEventHandler
      -com.bitnei.cloud.compent.kafka.handler.VehicleLoginKafkaHandler
      -com.bitnei.cloud.compent.kafka.handler.ForwordVehicleStatusHandler
    FAULT_PARAMETER_ALARM_TOPIC:
      -com.bitnei.cloud.fault.kafka.FaultParameterAlarmHandler
    FAULT_CODE_ALARM_TOPIC:
      -com.bitnei.cloud.fault.kafka.FaultCodeAlarmtHandler

  excutor:
    corePoolSize: 10
    keepAliveSeconds: 30000
    maxPoolSize: 20
    queueCapacity: 2000

ftp:
  publicHost: 114.251.179.119
  host: 192.168.1.103
  port: 21
  username: qiye
  password: v5EQryQqVjVM
  path: /opt/qiye
  mod: 1
  webDownlodefilePath: /opt/upload/file/downlodeFile/
