spring:
  kafka:
    bootstrap-servers: kafka01.bitnei.cn:9092,kafka02.bitnei.cn:9092,kafka03.bitnei.cn:9092
    producer:
      retries: 3

sender:
  vin-file-path: /opt/supp_app/vin.copy
  topic: us_packet_32960
  type: geely
  frequency: 10
