## 发动机型号添加字段
alter ignore  table sys_engine_model add (
	obd_model varchar(128) comment 'OBD型号',
	obd_unit_id varchar(36) comment 'OBD生产厂商',
	bus_protocol varchar(128) comment '总线协议',
	bus_type varchar(128) comment '总线类型',
	diagnostic_protocol varchar(128) comment '诊断协议',
	interface_location varchar(128) comment '接口位置',
	interface_type varchar(128) comment '接口类型',
	is_encrypt varchar(128) comment '是否加密',
	external_speed  varchar(128) comment '外特性-转速(r/min)',
	external_torque varchar(128) comment '外特性-扭矩(N.m) ',
	test_cycle_work varchar(128) comment 'ETC试验循环功（kWh）',
	cylinder_arrangement varchar(128) comment '气缸排列型式',
	swept_volume varchar(128) comment '发动机排量（L）',
	max_power_speed varchar(128) comment '最大功率/转速（kW/r/min）',
	max_torque_speed varchar(128) comment '最大扭矩/转速（Nm/r/min）',
	pcd_exhaust_type varchar(128) comment '排气后处理系统形式',
	etc_cycle_work varchar(128) comment 'ETC循环功',
	wthc_cycle_work varchar(128) comment 'WTHC循环功',
	engine_torque varchar(128) comment '参考扭矩',
	engine_rated_power varchar(128) comment '发动机额定功率',
	calid_software_sn varchar(128) comment '软件标定识别号（CALID）',
	cvn_calibration_code varchar(128) comment '标定验证码（CVN）',
	engine_arrangement varchar(128) comment '发动机布置方式',
	auxiliary_engine varchar(128) comment '是否有副发动机',
	auxiliary_emission varchar(128) comment '副发动机排放标准',
	auxiliary_firm varchar(128) comment '副发动机生产企业',
	auxiliary_fuel_type	 varchar(128) comment '副发动机燃料类型',
	combustion_chamber varchar(128) comment '燃烧室结构',
	compression_ratio varchar(128) comment '容积压缩比',
	cooling_method varchar(128) comment '冷却方式',
	cylinder_bore_stroke varchar(128) comment '缸数-缸径×行程（mm）',
	cylinder_pitch varchar(128) comment '发动机缸心距（mm）',
	cylinder_structure varchar(128) comment '缸体构造',
	ecu_hardware_model varchar(128) comment 'ECU电控单元（硬件）型号',
	ecu_hardware_firm varchar(128) comment 'ECU电控单元生产厂',
	ecu_software_model varchar(128) comment 'ECU软体型号',
	ecu_sftware_firm varchar(128) comment 'ECU软体生产厂',
	egr_model varchar(128) comment 'EGR型号',
	egr_firm varchar(128) comment 'EGR生产厂',
	fuel_sulfur varchar(128) comment '燃料及硫含量（10-6）',
	exhaust_back_pressure varchar(128) comment '排气背压（kPa）',
	fuel_supply_form varchar(128) comment '供油系统形式',
	governor_model varchar(128) comment '调速器型号',
	governor_firm varchar(128) comment '调速器生产厂',
	idle_speed varchar(128) comment '怠速转速（r/min）',
	engine_ignition_mode varchar(128) comment '发动机点火方式',
	injection_model varchar(128) comment '喷油器型号',
	injection_firm varchar(128) comment '喷油器生产厂',
	injector_pressure varchar(128) comment '喷油器喷射压力（MPa）',
	injection_pump_model varchar(128) comment '喷油泵型号',
	injection_pump_firm varchar(128) comment '喷油泵生产厂',
	intake_resistance varchar(128) comment '进气阻力(kPa)',
	intercooler_model varchar(128) comment '中冷器型号',
	intercooler_type varchar(128) comment '中冷器形式',
	intercooler_firm varchar(128) comment '中冷器生产厂',
	max_outlet_temperature varchar(128) comment '最高出口温度（℃）',
	max_empty_speed varchar(128) comment '最高空车转速（r/min）',
	maximum_net_power varchar(128) comment '最大净功率/转速',
	single_valve_num varchar(128) comment '单缸进/排气阀数',
	stroke_fuel_supply varchar(128) comment '最大扭矩转速时每冲程燃料供给量（ml）',
	rated_fuel_supply varchar(128) comment '额定功率转速时每冲程燃料供给量（ml）',
	turbo_charger_model varchar(128) comment '增压器型号',
	turbo_charger_firm varchar(128) comment '增压器生产厂',
	pcd_particulate_model varchar(128) comment '颗粒捕集器型号',
	pcd_particulate_position varchar(128) comment '颗粒捕集器安装位置',
	pcd_particulate_structure varchar(128) comment '颗粒物捕集器结构',
	pcd_particulate_type varchar(128) comment '颗粒物捕集器型式',
	pcd_particulate_volume varchar(128) comment '颗粒物捕集器容积（ml）',
	pcd_particulate_firm varchar(128) comment '颗粒捕集器生产厂',
	pcd_particulate_method varchar(128) comment '颗粒捕集器再生方法',
	post_processing_model varchar(128) comment '后处理控制器型号',
	post_processing_firm varchar(128) comment '后处理控制器生产厂',
	pcd_reactant_temperature varchar(128) comment '反应剂正常工作温度范围（K）',
	pcd_reactant_type varchar(128) comment '反应剂类型和浓度',
	pcd_reborn_temperature varchar(128) comment '再生的温度（K）及压力范围（kPa）',
	mileage_actual_val varchar(128) comment '尿素可用里程实际值',
	mileage_theoretical_val varchar(128) comment '尿素可用里程理论值',
	consume_actual_val varchar(128) comment '尿素消耗比例实际值',
	consume_theoretical_val varchar(128) comment '尿素消耗比例理论值',
	air_filter_model varchar(128) comment '空滤器型号',
	air_filter_firm varchar(128) comment '空滤器生产企业',
	air_injection_type varchar(128) comment '空气喷射系统型式',
	pcd_carrier_density varchar(128) comment '载体孔密度',
	pcd_carrier_material varchar(128) comment '载体材料及结构',
	pcd_carrier_firm varchar(128) comment '载体生产厂',
	pcd_catalytic_model varchar(128) comment '催化转化器型号',
	pcd_catalytic_material varchar(128) comment '催化器载体材料',
	pcd_catalytic_form varchar(128) comment '催化转化器作用形式',
	pcd_catalytic_num varchar(128) comment '催化转化器装车数量',
	pcd_catalytic_firm varchar(128) comment '催化转化器生产厂',
	pcd_catalytic_temperature varchar(128) comment '催化转化器正常温度范围（K）',
	pcd_catalytic_total varchar(128) comment '贵金属（催化剂）总含量（g）',
	pcd_catalytic_type varchar(128) comment '贵金属（催化剂）种类',
	catalytic_units_num varchar(128) comment '催化单元数目',
	pcd_catalytic_ratio varchar(128) comment '贵金属（催化剂）比例',
	pcd_catalytic_volume varchar(128) comment '催化转化器容积（ml）',
	etc_cycles_num varchar(128) comment '再生系统2次再生之间的ETC循环次数',
	exhaust_port_distance varchar(128) comment '后处理进气口据发动机排气口距离',
	heat_insulator varchar(128) comment '保温材料',
	is_consistent varchar(128) comment '是否与发动机认证一致',
	is_insulation varchar(128) comment '后处理是否保温',
	muffler_model varchar(128) comment '排气消声器型号',
	muffler_firm varchar(128) comment '排气消声器生产厂',
	no_sensor_type varchar(128) comment '氮氧传感器型号',
	no_sensor_firm varchar(128) comment '氮氧传感器生产厂',
	paint_coat_firm varchar(128) comment '涂层生产厂'
);


## 创建加密芯片型号表
DROP TABLE IF EXISTS sys_encryption_chip_model;
CREATE TABLE sys_encryption_chip_model(
	id varchar(36) NOT NULL COMMENT '主键',
	name varchar(128) COMMENT '芯片型号',
	unit_id varchar(36) COMMENT '芯片厂商',
	unit_declare varchar(100) COMMENT '厂商说明',
	licence_img_id varchar(36) COMMENT '厂商执照图片',
	qualification_img_id varchar(36) COMMENT '芯片资质图片',
	create_time varchar(20) DEFAULT NULL COMMENT '创建时间',
	create_by varchar(36) DEFAULT NULL COMMENT '创建人',
	update_time varchar(20) DEFAULT NULL COMMENT '更新时间',
	update_by varchar(36) DEFAULT NULL COMMENT '更新人',
	PRIMARY KEY (id),
	UNIQUE KEY unique_name (name) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='加密芯片型号|加密芯片型号|ecm';


## 创建加密芯片管理表
DROP TABLE IF EXISTS sys_encryption_chip;
CREATE TABLE sys_encryption_chip(
	id varchar(36) NOT NULL COMMENT '主键',
	identification_id varchar(13) COMMENT '安全芯片标识ID',
	chip_model_id varchar(36) COMMENT '芯片型号ID',
	filing_status tinyint(4) COMMENT '防篡改信息备案状态',
	private_key_status tinyint(4) COMMENT '私钥灌装状态',
	term_public_key varchar(128) COMMENT '终端公钥',
	create_time varchar(20) DEFAULT NULL COMMENT '创建时间',
	create_by varchar(36) DEFAULT NULL COMMENT '创建人',
	update_time varchar(20) DEFAULT NULL COMMENT '更新时间',
	update_by varchar(36) DEFAULT NULL COMMENT '更新人',
	PRIMARY KEY (id),
	UNIQUE KEY unique_identification (identification_id) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='加密芯片|加密芯片|ec';


## 终端型号添加字段 支持加密芯片
alter table sys_term_model add support_encryption_chip tinyint(4) comment '支持加密芯片';

## 终端信息添加字段 加密芯片ID

alter table sys_term_model_unit add encryption_chip_id varchar(36) comment '加密芯片ID';



## 车型型号 添加字段
alter table sys_veh_model_alarm add (
	engine_model varchar(128) comment '发动机型号',
	emission_level varchar(128) comment '排放标准',
	urea_tank_capacity varchar(128) comment '尿素箱容积(L)',
	vehicle_firm varchar(128) comment '整车生产企业',
	reduction_ratio varchar(128) comment '驱动桥主减速比',
	transmission_forward_num varchar(128) comment '前进档个数',
	transmission_gear_ratio varchar(128) comment '各档速比',
	use_type varchar(128) comment '用途类型',
	product_area varchar(128) comment '产地',
	max_allow_mass varchar(128) comment '最大允许装载质量',
	bearing_max_allow_mass varchar(128) comment '半挂牵引车鞍座最大允许承载质量',
	min_ground_clearance varchar(128) comment '最小离地间隙',
	veh_sliding_coefficient varchar(128) comment '车辆滑行系数(A、B、C)',
	axles_number varchar(128) comment '轴数/列车轴数',
	wheel_base varchar(128) comment '轴距(mm)',
	wheelbase_detail  varchar(128) comment '轮距(前/后)(mm)',
	body_model  varchar(128) comment '车身（或驾驶室）型式',
	tire_number  varchar(128) comment '轮胎数',
	tire_manufacturer  varchar(128) comment '轮胎生产企业',
	tire_spec  varchar(128) comment '轮胎规格',
	tire_pressure  varchar(128) comment '轮胎气压(kPa)',
	approach_departure_angle  varchar(128) comment '接近角/离去角(°)',
	transmission_name  varchar(128) comment '变速箱',
	transmission_model  varchar(128) comment '变速器型号',
	transmission_firm  varchar(128) comment '变速器生产企业',
	transmission_type  varchar(128) comment '型式/操纵方式',
	fuel_tank_capacity  varchar(128) comment '油箱容积',
	allowed_max_power  varchar(128) comment '由发动机驱动的附件允许吸收的最大功率(kW)',
	abc_speed  varchar(128) comment 'ESC试验ABC转速(r/min)',
	tms_monitor_version  varchar(128) comment '设备监控版本号',
	drive_type  varchar(128) comment '驱动型式及位置'
);
