CREATE TABLE `fault_veh_risk_notice` (
  `id` varchar(36) NOT NULL COMMENT 'id',
  `vin` varchar(45) DEFAULT NULL COMMENT 'vin',
  `vid` int(36) DEFAULT NULL COMMENT 'vid',
  `name` varchar(500) DEFAULT NULL COMMENT '报警提醒名称',
  `notice_type` varchar(500) DEFAULT NULL COMMENT '通知种类',
  `notice_status` tinyint(4) DEFAULT NULL COMMENT '通知状态',
  `read_status` tinyint(1) DEFAULT NULL COMMENT '消息状态(0未读1已读)',
  `risk_level` tinyint(4) DEFAULT NULL COMMENT '风险等级',
`notice_original_text` varchar(500) DEFAULT NULL COMMENT '通知原文',
  `annotations` varchar(500) DEFAULT NULL COMMENT '批注',
  `first_notice_time` varchar(20) DEFAULT NULL COMMENT '首次通知时间',
  `state_update_time` varchar(20) DEFAULT NULL COMMENT '状态更新时间',
  `alarm_status` varchar(500) DEFAULT NULL COMMENT '车辆报警状态',
  `read_time` varchar(20) DEFAULT NULL COMMENT '已读时间',
  `processing_time` varchar(20) DEFAULT NULL COMMENT '处理时间',
  `opinion` varchar(500) DEFAULT NULL COMMENT '国家平台管理员意见',
  `last_operator` varchar(36) DEFAULT NULL COMMENT '最近一次操作人员',
  `create_time` varchar(20) DEFAULT NULL COMMENT '创建时间',
  `create_by` varchar(36) DEFAULT NULL COMMENT '创建人',
  `update_time` varchar(20) DEFAULT NULL COMMENT '更新时间',
  `update_by` varchar(36) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='当前国家平台车辆风险通知|当前国家平台车辆风险通知|vrn';